image: brunoocto/lincko_php:latest

# Jobs to be taken into account by the CI
stages:
  - test
  - report
  - tag

# Run PHPunit and generate report
unit_test:
  stage: test
  tags:
    - docker
  cache:
    paths:
      - vendor/
  before_script:
    # PHPunit
    - cd /tmp
    - wget https://phar.phpunit.de/phpunit-8.phar -O phpunit
    - mv ./phpunit /usr/bin
    - chmod a+x /usr/bin/phpunit
    # Composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    # SSH login
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - if [[ -e /.dockerenv ]]; then echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config; fi;
    # Copy PHP configuration (for test only)
    - echo "$TEST_INI" > /usr/local/etc/php/conf.d/test.ini
  script:
    - cd $CI_PROJECT_DIR
    # Avoid an error because the folder does not exists
    - mkdir ./packages
    - composer install
    - phpunit --coverage-text --colors=never --configuration phpunit.xml
  artifacts:
    when: always
    expire_in: 1 days
    paths:
      - reports

# Publish report on "pages" feature of Gitlab
pages:
  stage: report
  tags:
    - docker
  dependencies:
    - unit_test
  script:
    - mv reports/ public/
  artifacts:
    paths:
      - public
    expire_in: 4 weeks
  only:
    - master

# Generate a new tag syncrhonized with comnposer.json information
tag_creation:
  stage: tag
  tags:
    - docker
  dependencies:
    - unit_test
  script:
    # SSH login
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - if [[ -e /.dockerenv ]]; then echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config; fi
    # Enable git remote operation
    - git remote set-url origin git@gitlab.com:${CI_PROJECT_PATH}.git
    # Grab and push version number
    - cd $CI_PROJECT_DIR
    - >
      tag_version=$(cat composer.json | grep -oP '(?<="version": ")v?[\d.]+(?=",)');
      if [ -z ${tag_version} ];
      then
        echo "Missing version number in composer, or wrong format.";
        exit 1;
      fi;
    # Create the tag if it does not exists
    - >
      if [ -z "$(git tag -l ${tag_version})" ];
      then
        git tag -a ${tag_version} -m "Version ${tag_version}";
      fi;
    # Push the tag if it does not exists remotely
    - >
      if [ -z "$(git ls-remote origin refs/tags/${tag_version})" ];
      then
        git push origin ${tag_version};
      fi;
  only:
    - master
